// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_-sRci9F_XFiIB1GIF9M6Qb8niAetmKM',
    appId: '1:929683755212:web:9de42305d223746758f269',
    messagingSenderId: '929683755212',
    projectId: 'notes-d5a40',
    authDomain: 'notes-d5a40.firebaseapp.com',
    storageBucket: 'notes-d5a40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77FzXySdhqzyeagakQ9NzErkzJFvt9_E',
    appId: '1:929683755212:android:b4dea3329b56b6c558f269',
    messagingSenderId: '929683755212',
    projectId: 'notes-d5a40',
    storageBucket: 'notes-d5a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0REgAINVB9pwRZ802NUWHg2B8Zu4RPpU',
    appId: '1:929683755212:ios:b26efeadebcd514558f269',
    messagingSenderId: '929683755212',
    projectId: 'notes-d5a40',
    storageBucket: 'notes-d5a40.appspot.com',
    iosClientId: '929683755212-lul0kbiufqhjnreor6r6ui3b1il8celc.apps.googleusercontent.com',
    iosBundleId: 'com.example.major',
  );
}
